version: '3.4'

volumes:
  redis_data:
  redis_insight_data:


networks:
  backend-network:


services:
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      # - REDIS_PASSWORD=redis_password
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      # use memory instead of disk
      - REDIS_APPENDONLY=no
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - backend-network

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - 'redis_insight_data:/db'
    networks:
      - backend-network
