version: '3.4'

volumes:
  redis_data:
  redis_insight_data:


networks:
  no-internet:
    internal: true
    driver: bridge
  exposed:
    internal: false
    driver: bridge

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      REDIS_HOST: redis:6379
    ports:
      - 3000:3000
    networks:
      - no-internet
      - exposed

  # app-internal:
  #   image: app
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   environment:
  #     REDIS_HOST: redis:6379
  #   networks:
  #     - no-internet
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 512M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 256M

  # redis:
  #   image: docker.io/bitnami/redis:7.2
  #   environment:
  #     # - REDIS_PASSWORD=redis_password
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #     # use memory instead of disk
  #     - REDIS_APPENDONLY=no
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - 'redis_data:/bitnami/redis/data'
  #   networks:
  #     - no-internet

  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   ports:
  #     - '8001:8001'
  #   volumes:
  #     - 'redis_insight_data:/db'
  #   networks:
  #     - no-internet

  loadtest:
    image: "loadtest"
    build:
      context: loadtest
      dockerfile: ./Dockerfile
    environment:
      LOADTEST_URL: "http://app:3000/add"
      LOADTEST_VUS: 10000
      LOADTEST_ITERATIONS: 1000000
      LOADTEST_DURATION: "5m"
    depends_on:
      # - redis
      - app
    networks:
      - no-internet
    # 10 replicas
    deploy:
      mode: replicated
      replicas: 10
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
        reservations:
          cpus: '0.50'
          memory: 1G
  # ubuntu:
  #   image: ubuntu
  #   command: sleep infinity
  #   networks:
  #     - no-internet
