version: '3.4'

volumes:
  redis_data:
  redis_insight_data:


networks:
  no-internet:
    # internal: true
    # driver: bridge
    driver: overlay
  exposed:
    # internal: false
    # driver: overlay
    driver: overlay

services:
  app:
    image: docker.io/wuttinanhi/1millionconnectionchallenge-app:latest
    environment:
      REDIS_HOST: redis:6379
    ports:
      - 3000:3000
    networks:
      - no-internet
      - exposed
    deploy:
      # mode: global
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1.00'
          memory: 5G
        reservations:
          cpus: '1.00'
          memory: 1G

  loadtest:
    image: docker.io/wuttinanhi/1millionconnectionchallenge-loadtest:latest
    environment:
      LOADTEST_URL: "http://app:3000/add"
      # LOADTEST_VUS: 10000
      # LOADTEST_ITERATIONS: 1000000
      # LOADTEST_DURATION: "5m"
    depends_on:
      - app
    networks:
      - no-internet
    deploy:
      mode: replicated
      # mode: replicated-job
      replicas: 7
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '1.00'
          memory: 10G
        reservations:
          cpus: '1.00'
          memory: 2G
      restart_policy:
        condition: none
